### ISSUE TITLE
cant run md5.py

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [rgbcpu/CompSec_Proj2#1]
hi I was just wondering i cant run md5.py and i think you forgot to include python in your project.  I attached a pciture of the eror message i get. please help????????
![python](https://user-images.githubusercontent.com/57604669/69489781-95614900-0e43-11ea-8b11-b4d79efafb74.png)

**Comment by SamFissure** [comment]
Not sure about the commands on a Windows system.  We ran it on a Unix system, and the needed command was either Python3 or Python 3 (can't remember, haven't used Python enough on that server).  

Critically, you need Python 3 to run it.  On windows, I used the default IDE to run it.

**Comment by SamFissure** [comment]
Also, and this is key, launching this, and many other Python programs, via double click and the like on Windows while not using an IDE will lead to the program terminating early.  This is true for many, if not most Python programs.  To avoid this, other code has to be added to prevent it from terminating early.  
This is why it's best to run this in an IDE and or a non-Windows environment.

**Comment by SamFissure** [comment]
Finally, the final product is the one labeled Final Final Final.  We didn't implement standard Git version control on the project, thus didn't overwrite our files.  You don't need every file, just the one.
